### ISSUE TITLE
General framework for map/search sites containing small amounts of geo data

### ISSUE THREAD

**Issue by ohnorobo** [codeforboston/lgbtq-data#1]
I think it would be interesting to look into something client-side like [filter.js](https://github.com/jiren/filter.js) so we could throw up simple static sites (through gh-pages) for any little data sets we get.

[map demo](http://jiren.github.io/filter.js/filterjs-map.html), [filter demo](http://jiren.github.io/filter.js/filterjs.html)

**Comment by calvinmetcalf** [comment]
I think filter.js is a bit overkill I can whip up a leaflet template for you next meeting

**Comment by calvinmetcalf** [comment]
[here we go](https://github.com/codeforboston/filter-template)

**Comment by ohnorobo** [comment]
Thank you :) 
I was specifically looking into filter.js because we'd been discussing search interfaces for both this data and pantry pickup, and we need simple ways to search over the non-geospacial data. (In this dataset that would be things like organization name, services offered, target populations, and age ranges) I liked the keyword/facet/range search elements. 
Does filter.js still strike you as too heavy for that sort of thing? Other recommendations?

The other element is the ability to search by location/proximity. I don't know what (if any) possibilities there are for doing that client side.

**Comment by calvinmetcalf** [comment]
I usually just put that kind of complex filtering into a backbone view, if you need geospatial searching [rtree](https://github.com/leaflet-extras/RTree) is a good bet if your not doing it server side (from what I understand mongo has limited spatial abilities).

**Comment by ohnorobo** [comment]
https://github.com/codeforboston/finda/
